<?php

namespace Database\Seeders;

use App\Models\Privilege;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PrivilegesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $privileges = [
            [
                'id'          => Str::uuid(),
                'name'        => 'User - List Paginate',
                'description' => 'UserController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'User - Detail',
                'description' => 'UserController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'User - Create',
                'description' => 'UserController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'User - Update',
                'description' => 'UserController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'User - Delete',
                'description' => 'UserController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'User - Change',
                'description' => 'UserController@changePassword',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Role - List All',
                'description' => 'RoleController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Role - List Paginate',
                'description' => 'RoleController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Role - Detail',
                'description' => 'RoleController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Role - Create',
                'description' => 'RoleController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Role - Update',
                'description' => 'RoleController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Role - Delete',
                'description' => 'RoleController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Role - Privileges',
                'description' => 'RoleController@getPrivileges',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Privilege - List Paginate',
                'description' => 'PrivilegeController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Privilege - List All',
                'description' => 'PrivilegeController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Privilege - Detail',
                'description' => 'PrivilegeController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Privilege - Create',
                'description' => 'PrivilegeController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Privilege - Update',
                'description' => 'PrivilegeController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Privilege - Delete',
                'description' => 'PrivilegeController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ActiveLog - List All',
                'description' => 'ActiveLogController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ActiveLog - List Paginate',
                'description' => 'ActiveLogController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ActiveLog - Detail',
                'description' => 'ActiveLogController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ActiveLog - Update',
                'description' => 'ActiveLogController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ActiveLog - share',
                'description' => 'ActiveLogController@share',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ActiveLog - Delete',
                'description' => 'ActiveLogController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Shop - List All',
                'description' => 'ShopController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Shop - List Paginate',
                'description' => 'ShopController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Shop - Detail',
                'description' => 'ShopController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Shop - Create',
                'description' => 'ShopController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Shop - Update',
                'description' => 'ShopController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Shop - Delete',
                'description' => 'ShopController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Category - List All',
                'description' => 'CategoryController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Category - List Paginate',
                'description' => 'CategoryController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Category - Detail',
                'description' => 'CategoryController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Category - Create',
                'description' => 'CategoryController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Category - Update',
                'description' => 'CategoryController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Category - Delete',
                'description' => 'CategoryController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'SubCategory - List All',
                'description' => 'SubCategoryController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'SubCategory - List Paginate',
                'description' => 'SubCategoryController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'SubCategory - Detail',
                'description' => 'SubCategoryController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'SubCategory - Create',
                'description' => 'SubCategoryController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'SubCategory - Update',
                'description' => 'SubCategoryController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'SubCategory - Delete',
                'description' => 'SubCategoryController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Product - List All',
                'description' => 'ProductController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Product - List Paginate',
                'description' => 'ProductController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Product - Detail',
                'description' => 'ProductController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Product - Create',
                'description' => 'ProductController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Product - Update',
                'description' => 'ProductController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Product - Delete',
                'description' => 'ProductController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ProductInformation - List All',
                'description' => 'ProductInformationController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ProductInformation - List Paginate',
                'description' => 'ProductInformationController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ProductInformation - Detail',
                'description' => 'ProductInformationController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ProductInformation - Create',
                'description' => 'ProductInformationController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ProductInformation - Update',
                'description' => 'ProductInformationController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ProductInformation - Delete',
                'description' => 'ProductInformationController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Order - List All',
                'description' => 'OrderController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Order - List Paginate',
                'description' => 'OrderController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Order - Detail',
                'description' => 'OrderController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'DeliveryPerson - List All',
                'description' => 'DeliveryPersonController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'DeliveryPerson - List Paginate',
                'description' => 'DeliveryPersonController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'DeliveryPerson - Detail',
                'description' => 'DeliveryPersonController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'DeliveryPerson - Create',
                'description' => 'DeliveryPersonController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'DeliveryPerson - Update',
                'description' => 'DeliveryPersonController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'DeliveryPerson - Delete',
                'description' => 'DeliveryPersonController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Advisement - List All',
                'description' => 'AdvisementController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Advisement - List Paginate',
                'description' => 'AdvisementController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Advisement - Detail',
                'description' => 'AdvisementController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Advisement - Create',
                'description' => 'AdvisementController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Advisement - Update',
                'description' => 'AdvisementController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Advisement - Delete',
                'description' => 'AdvisementController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Banner - List All',
                'description' => 'BannerController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Banner - List Paginate',
                'description' => 'BannerController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Banner - Detail',
                'description' => 'BannerController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Banner - Create',
                'description' => 'BannerController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Banner - Update',
                'description' => 'BannerController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Banner - Delete',
                'description' => 'BannerController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Blog - List All',
                'description' => 'BlogController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Blog - List Paginate',
                'description' => 'BlogController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Blog - Detail',
                'description' => 'BlogController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Blog - Create',
                'description' => 'BlogController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Blog - Update',
                'description' => 'BlogController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Blog - Delete',
                'description' => 'BlogController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopType - List All',
                'description' => 'ShopTypeController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopType - List Paginate',
                'description' => 'ShopTypeController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopType - Detail',
                'description' => 'ShopTypeController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopType - Create',
                'description' => 'ShopTypeController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopType - Update',
                'description' => 'ShopTypeController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopType - Delete',
                'description' => 'ShopTypeController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopDocument - List All',
                'description' => 'ShopDocumentController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopDocument - List Paginate',
                'description' => 'ShopDocumentController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopDocument - Detail',
                'description' => 'ShopDocumentController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopDocument - Create',
                'description' => 'ShopDocumentController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopDocument - Update',
                'description' => 'ShopDocumentController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopDocument - Delete',
                'description' => 'ShopDocumentController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Avatar - List All',
                'description' => 'AvatarController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Avatar - List Paginate',
                'description' => 'AvatarController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Avatar - Detail',
                'description' => 'AvatarController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Avatar - Create',
                'description' => 'AvatarController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Avatar - Update',
                'description' => 'AvatarController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Avatar - Delete',
                'description' => 'AvatarController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Address - List All',
                'description' => 'AddressController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Address - List Paginate',
                'description' => 'AddressController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Address - Detail',
                'description' => 'AddressController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Address - Create',
                'description' => 'AddressController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Address - Update',
                'description' => 'AddressController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Address - Delete',
                'description' => 'AddressController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'AboutUs - List Paginate',
                'description' => 'AboutUsController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'AboutUs - Detail',
                'description' => 'AboutUsController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'AboutUs - Create',
                'description' => 'AboutUsController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'AboutUs - Update',
                'description' => 'AboutUsController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'AboutUs - Delete',
                'description' => 'AboutUsController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Career - List Paginate',
                'description' => 'CareerController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Career - Detail',
                'description' => 'CareerController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Career - Create',
                'description' => 'CareerController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Career - Update',
                'description' => 'CareerController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Career - Delete',
                'description' => 'CareerController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'PrivacyPolicy - List Paginate',
                'description' => 'PrivacyPolicyController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'PrivacyPolicy - Detail',
                'description' => 'PrivacyPolicyController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'PrivacyPolicy - Create',
                'description' => 'PrivacyPolicyController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'PrivacyPolicy - Update',
                'description' => 'PrivacyPolicyController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'PrivacyPolicy - Delete',
                'description' => 'PrivacyPolicyController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Security - List Paginate',
                'description' => 'SecurityPageController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Security - Detail',
                'description' => 'SecurityPageController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Security - Create',
                'description' => 'SecurityPageController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Security - Update',
                'description' => 'SecurityPageController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Security - Delete',
                'description' => 'SecurityPageController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Term - List Paginate',
                'description' => 'TermController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Term - Detail',
                'description' => 'TermController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Term - Create',
                'description' => 'TermController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Term - Update',
                'description' => 'TermController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'Term - Delete',
                'description' => 'TermController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'DeliveryPage - List Paginate',
                'description' => 'DeliveryPageController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'DeliveryPage - Detail',
                'description' => 'DeliveryPageController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'DeliveryPage - Create',
                'description' => 'DeliveryPageController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'DeliveryPage - Update',
                'description' => 'DeliveryPageController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'DeliveryPage - Delete',
                'description' => 'DeliveryPageController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopPage - List Paginate',
                'description' => 'ShopPageController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopPage - Detail',
                'description' => 'ShopPageController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopPage - Create',
                'description' => 'ShopPageController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopPage - Update',
                'description' => 'ShopPageController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopPage - Delete',
                'description' => 'ShopPageController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ContactUs - List Paginate',
                'description' => 'ContactUsController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ContactUs - Detail',
                'description' => 'ContactUsController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ContactUs - Create',
                'description' => 'ContactUsController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ContactUs - Update',
                'description' => 'ContactUsController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ContactUs - Delete',
                'description' => 'ContactUsController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'DeliveryPersonBankAccount - List All',
                'description' => 'DeliveryPersonBankAccountController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'DeliveryPersonBankAccount - List Paginate',
                'description' => 'DeliveryPersonBankAccountController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'DeliveryPersonBankAccount - Detail',
                'description' => 'DeliveryPersonBankAccountController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'DeliveryPersonBankAccount - Create',
                'description' => 'DeliveryPersonBankAccountController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'DeliveryPersonBankAccount - Update',
                'description' => 'DeliveryPersonBankAccountController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'DeliveryPersonBankAccount - Delete',
                'description' => 'DeliveryPersonBankAccountController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'DeliveryPersonBankAccount - Verify',
                'description' => 'DeliveryPersonBankAccountController@verify',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopBankAccount - List All',
                'description' => 'ShopBankAccountController@getAll',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopBankAccount - List Paginate',
                'description' => 'ShopBankAccountController@getPaginate',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopBankAccount - Detail',
                'description' => 'ShopBankAccountController@get',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopBankAccount - Create',
                'description' => 'ShopBankAccountController@create',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopBankAccount - Update',
                'description' => 'ShopBankAccountController@update',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopBankAccount - Delete',
                'description' => 'ShopBankAccountController@delete',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
            [
                'id'          => Str::uuid(),
                'name'        => 'ShopBankAccount - Verify',
                'description' => 'ShopBankAccountController@verify',
                'created_at'  => now(),
                'updated_at'  => null,
            ],
        ];

        Privilege::insert($privileges);
    }
}
