<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\SubCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        // Get subcategories
        $cheeseSubCategory     = SubCategory::where('name', 'Cheese')->first();
        $breadSubCategory      = SubCategory::where('name', 'Bread & Pav')->first();
        $butterSubCategory     = SubCategory::where('name', 'Butter & More')->first();
        $creamSubCategory      = SubCategory::where('name', 'Cream & Whitener')->first();
        $curdSubCategory       = SubCategory::where('name', 'Curd & Lassi')->first();
        $milkSubCategory       = SubCategory::where('name', 'Milk')->first();
        $eggsSubCategory       = SubCategory::where('name', 'Eggs')->first();
        $chipsSubCategory      = SubCategory::where('name', 'Chips & Crisps')->first();
        $softDrinksSubCategory = SubCategory::where('name', 'Soft Drinks')->first();

        $products = [
            // Cheese products
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $cheeseSubCategory ? $cheeseSubCategory->id : null,
                'name'            => 'Amul Pure Milk Cheese Slices',
                'image'           => Storage::disk('public')->url('products/Amul_Pure_Milk_Cheese_Slices.png'),
                'weight'          => '200 g',
                'price'           => 118.00,
                'original_price'  => 125.00,
                'discount'        => '5%',
                'delivery_time'   => 10,
                'about_product'   => 'Enjoy the real taste of India With Amul Cheese Slices. The Amul cheese is made from the graded milk and by using microbial Renne. Sliced cheese is a great source of milk proteins, vitamins and other nutrients. It can be used in hundreds of ways in any dish. Its delicate flavoured ingredient gives a lip-smacking flavour to every dish. Cheese is a delicious component and is also used in the preparation of sweet dishes.',
                'unit'            => '10',
                'product_code'    => 'DBE006-001',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            // Bread products
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $breadSubCategory ? $breadSubCategory->id : null,
                'name'            => 'Britannia Milk Bread',
                'image'           => Storage::disk('public')->url('products/Britannia_Milk_Bread.png'),
                'weight'          => '400 g',
                'price'           => 50.00,
                'original_price'  => 45.00,
                'discount'        => null,
                'delivery_time'   => 10,
                'about_product'   => 'Britannia Milk Bread is made with the goodness of milk which makes it soft, fluffy and delicious. Ideal for sandwiches, toasts or just as it is. Contains added vitamins and minerals for extra nutrition.',
                'unit'            => '10',
                'product_code'    => 'DBE002-001',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            // Butter products
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $butterSubCategory ? $butterSubCategory->id : null,
                'name'            => 'Amul Salted Butter',
                'image'           => Storage::disk('public')->url('products/Amul_Salted_Butter.png'),
                'weight'          => '200 g',
                'price'           => 144.00,
                'original_price'  => 145.00,
                'discount'        => null,
                'delivery_time'   => 10,
                'about_product'   => 'Amul Butter is made from fresh cream and contains natural milk fat. The salted variant has a rich, creamy taste with a perfect balance of salt. Ideal for spreading on bread, toast, or for cooking and baking purposes.',
                'unit'            => '10',
                'product_code'    => 'DBE005-001',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            // Cream products
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $creamSubCategory ? $creamSubCategory->id : null,
                'name'            => 'Amul Mithai Mate Condensed Milk',
                'image'           => Storage::disk('public')->url('products/Amul_Mithai_Mate_Condensed_Milk.png'),
                'weight'          => '500 g',
                'price'           => 285.00,
                'original_price'  => null,
                'discount'        => null,
                'delivery_time'   => 10,
                'about_product'   => 'Amul Mithai Mate is sweetened condensed milk specially prepared for making Indian sweets. It has a rich, creamy texture and sweet taste that enhances the flavor of traditional Indian desserts like gulab jamun, peda, and barfi.',
                'unit'            => '10',
                'product_code'    => 'DBE007-001',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            // Curd products
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $curdSubCategory ? $curdSubCategory->id : null,
                'name'            => 'Nandini Curd',
                'image'           => Storage::disk('public')->url('products/Nandini_Curd.png'),
                'weight'          => '500 g',
                'price'           => 26.00,
                'original_price'  => null,
                'discount'        => null,
                'delivery_time'   => 10,
                'about_product'   => 'Nandini Curd is made from pure cow milk and contains live cultures. It has a thick, creamy texture and mildly tangy taste. Rich in probiotics that aid digestion and boost immunity. Perfect for eating as is or using in raitas, kadhi, and other dishes.',
                'unit'            => '10',
                'product_code'    => 'DBE008-001',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $curdSubCategory ? $curdSubCategory->id : null,
                'name'            => 'Nandini Mango Lassi',
                'image'           => Storage::disk('public')->url('products/Nandini_Mango_Lassi.png'),
                'weight'          => '200 ml',
                'price'           => 35.00,
                'original_price'  => 40.00,
                'discount'        => '13%',
                'delivery_time'   => 10,
                'about_product'   => 'Nandini Mango Lassi is a refreshing yogurt-based drink blended with real mango pulp. Rich in probiotics and vitamins, it makes for a perfect summer cooler or healthy snack any time of the day.',
                'unit'            => '10',
                'product_code'    => 'DBE008-002',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            // Milk products
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $milkSubCategory ? $milkSubCategory->id : null,
                'name'            => 'Nandini Toned Fresh Milk',
                'image'           => Storage::disk('public')->url('products/Nandini_Toned_Fresh_Milk.png'),
                'weight'          => '1 liter',
                'price'           => 66.00,
                'original_price'  => null,
                'discount'        => null,
                'delivery_time'   => 10,
                'about_product'   => 'Nandini Toned Milk is fresh, pure and homogenized milk with 3% fat. It is rich in proteins, calcium and other essential nutrients. Pasteurized for safety while retaining natural goodness. Ideal for daily consumption, tea/coffee, and cooking.',
                'unit'            => '10',
                'product_code'    => 'DBE001-001',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $milkSubCategory ? $milkSubCategory->id : null,
                'name'            => 'Nandini Shubham Fresh Milk',
                'image'           => Storage::disk('public')->url('products/Nandini_Shubham_Fresh_Milk.png'),
                'weight'          => '1 liter',
                'price'           => 118.00,
                'original_price'  => 125.00,
                'discount'        => '5%',
                'delivery_time'   => 10,
                'about_product'   => 'Nandini Shubham is premium full cream milk with 6% fat. It is rich, creamy and packed with nutrients. Perfect for making paneer, sweets, or for those who prefer richer milk. Homogenized and pasteurized for safety.',
                'unit'            => '10',
                'product_code'    => 'DBE001-002',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            // Egg products
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $eggsSubCategory ? $eggsSubCategory->id : null,
                'name'            => 'Jaya White Eggs',
                'image'           => Storage::disk('public')->url('products/Jaya_White_Eggs.png'),
                'weight'          => '6 pieces',
                'price'           => 50.00,
                'original_price'  => 45.00,
                'discount'        => null,
                'delivery_time'   => 10,
                'about_product'   => 'Jaya White Eggs are farm fresh eggs with strong shells and rich, golden yolks. A great source of high-quality protein, vitamins and minerals. Perfect for boiling, frying, baking or any style of cooking.',
                'unit'            => '10',
                'product_code'    => 'DBE003-001',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $eggsSubCategory ? $eggsSubCategory->id : null,
                'name'            => 'Table White Eggs',
                'image'           => Storage::disk('public')->url('products/Table_White_Eggs.png'),
                'weight'          => '30 pieces',
                'price'           => 60.00,
                'original_price'  => 65.00,
                'discount'        => '8%',
                'delivery_time'   => 10,
                'about_product'   => 'Table White Eggs are naturally raised eggs from free-range hens. They have darker yolks and richer flavor compared to regular eggs. Higher in omega-3 fatty acids and vitamins. Ideal for those who prefer organic-style eggs.',
                'unit'            => '10',
                'product_code'    => 'DBE003-002',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            // Chips & Crisps products
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $chipsSubCategory ? $chipsSubCategory->id : null,
                'name'            => 'Lay\'s West Indies Hot n Sweet Chilli Flavor Potato Chips',
                'image'           => Storage::disk('public')->url('products/Lays_West_Indies_Hot_n_Sweet_Chilli_Flavor_Potato_Chips.png'),
                'weight'          => '50 g',
                'price'           => 19.00,
                'original_price'  => 20.00,
                'discount'        => '5%',
                'delivery_time'   => 20,
                'about_product'   => 'Lay\'s West Indies Hot \'n\' Sweet Chilli flavour will ignite your tastebuds. Made from the highest quality, farm-grown potatoes. Lay\'s West Indies Hot \'n\' Sweet Chilli is a 100% vegetarian snack. A versatile snack that can be enjoyed in any setting.',
                'unit'            => '20',
                'product_code'    => 'SNK001-001',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $chipsSubCategory ? $chipsSubCategory->id : null,
                'name'            => 'Lay\'s India\'s Magic Masala Potato Chips',
                'image'           => Storage::disk('public')->url('products/Lays_Indias_Magic_Masala_Potato_Chips.png'),
                'weight'          => '50 g',
                'price'           => 19.00,
                'original_price'  => 20.00,
                'discount'        => '5%',
                'delivery_time'   => 20,
                'about_product'   => 'Potato, edible vegetable oil (palmolein, rice bran oil), *seasoning (~spices and condiments, iodized salt, maltodextrin, black salt, sugar, tomato powder, acidity regulators (330, 296, 334), flavour (natural and nature identical flavouring substances), anticaking agent (551), color (160c)). *As flavouring agent. ~Contains Onion and Garlic.',
                'unit'            => '20',
                'product_code'    => 'SNK001-002',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $chipsSubCategory ? $chipsSubCategory->id : null,
                'name'            => 'Beyond Snack Kerala Salt & Pepper Banana Chips',
                'image'           => Storage::disk('public')->url('products/Beyond_Snack_Kerala_Salt_Pepper_Banana_Chips.png'),
                'weight'          => '100 g',
                'price'           => 74.00,
                'original_price'  => 75.00,
                'discount'        => '1%',
                'delivery_time'   => 20,
                'about_product'   => 'Salt & Pepper flavored banana chips made from Kerala bananas. Crunchy and delicious snack perfect for any time munching.',
                'unit'            => '5',
                'product_code'    => 'SNK001-003',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $chipsSubCategory ? $chipsSubCategory->id : null,
                'name'            => 'Chheda\'s Long Masala Banana Chips',
                'image'           => Storage::disk('public')->url('products/Chhedas_Long_Masala_Banana_Chips.png'),
                'weight'          => '150 g',
                'price'           => 88.00,
                'original_price'  => 95.00,
                'discount'        => '7%',
                'delivery_time'   => 20,
                'about_product'   => 'Masala flavored long banana chips with traditional Indian spices. A perfect combination of crunch and flavor.',
                'unit'            => '5',
                'product_code'    => 'SNK001-004',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $chipsSubCategory ? $chipsSubCategory->id : null,
                'name'            => 'Lay\'s American Style Cream & Onion Potato Chips',
                'image'           => Storage::disk('public')->url('products/Lays_American_Style_Cream_Onion_Potato_Chips.png'),
                'weight'          => '50 g',
                'price'           => 20.00,
                'original_price'  => 20.00,
                'discount'        => null,
                'delivery_time'   => 20,
                'about_product'   => 'The American style cream and onion chips are topped with an exquisite blend of delicious flavours. Made from the highest quality, farm-grown potatoes.',
                'unit'            => '10',
                'product_code'    => 'SNK001-005',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $chipsSubCategory ? $chipsSubCategory->id : null,
                'name'            => 'Lay\'s Chile Limon Flavour Potato Chips',
                'image'           => Storage::disk('public')->url('products/Lays_Chile_Limon_Flavour_Potato_Chips.png'),
                'weight'          => '50 g',
                'price'           => 20.00,
                'original_price'  => 20.00,
                'discount'        => null,
                'delivery_time'   => 20,
                'about_product'   => 'Lay\'s Chile Limon potato chips are perfectly seasoned for an intense kick of tangy flavour. Made from the highest quality, farm-grown potatoes. A 100% vegetarian snack that can be enjoyed in any setting.',
                'unit'            => '10',
                'product_code'    => 'SNK001-006',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            // Soft Drinks products
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $softDrinksSubCategory ? $softDrinksSubCategory->id : null,
                'name'            => 'Coca-Cola Diet Coke Diets & Lights',
                'image'           => Storage::disk('public')->url('products/Coca-Cola_Diet_Coke_Diets_Lights.png'),
                'weight'          => '500 ml',
                'price'           => 40.00,
                'original_price'  => 40.00,
                'discount'        => null,
                'delivery_time'   => 20,
                'about_product'   => 'A lighter and crisper Coca-Cola. Contains Less than 1 Calorie, ideal for the calorie conscious. Enjoy Coca-Cola delicious taste with meals or on the go. Create moments for yourself with your our own can of refreshing Diet Coke.',
                'unit'            => '10',
                'product_code'    => 'CDJ001-001',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $softDrinksSubCategory ? $softDrinksSubCategory->id : null,
                'name'            => 'Thums Up Cola Soft Drink',
                'image'           => Storage::disk('public')->url('products/Thums_Up_Cola_Soft_Drink.png'),
                'weight'          => '500 ml',
                'price'           => 44.00,
                'original_price'  => 45.00,
                'discount'        => '2%',
                'delivery_time'   => 10,
                'about_product'   => 'Strong taste: Refresh yourself with the strong taste of thums up. Spicy & fizzy: This strong, spicy and fizzy cold drink is designed to suit your palate. Taste the thunder: Bring out the adventurous side of you with the thunderous taste of thums up drink.',
                'unit'            => '10',
                'product_code'    => 'CDJ001-002',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $softDrinksSubCategory ? $softDrinksSubCategory->id : null,
                'name'            => 'Coca-Cola Soft Drink',
                'image'           => Storage::disk('public')->url('products/Coca-Cola_Soft_Drink.png'),
                'weight'          => '750 ml',
                'price'           => 44.00,
                'original_price'  => 45.00,
                'discount'        => '2%',
                'delivery_time'   => 10,
                'about_product'   => 'Original cola flavour: Savor the refreshing cola flavor that is deliciously uplifting. Turn up the energy: Turn up the energy with the delicious and refreshing taste of coca-cola original. Make meals tastier: Meals become tastier with coca-cola original.',
                'unit'            => '10',
                'product_code'    => 'CDJ001-003',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $softDrinksSubCategory ? $softDrinksSubCategory->id : null,
                'name'            => '7UP Nimbooz with Lemon Juice',
                'image'           => Storage::disk('public')->url('products/7UP_Nimbooz_with_Lemon_Juice.png'),
                'weight'          => '500 ml',
                'price'           => 25.00,
                'original_price'  => 25.00,
                'discount'        => null,
                'delivery_time'   => 10,
                'about_product'   => 'Refreshing soft drink made with real lemon juice. Offers a lip-smacking tangy taste in every sip. Perfect thirst quencher for summers.',
                'unit'            => '10',
                'product_code'    => 'CDJ001-004',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $softDrinksSubCategory ? $softDrinksSubCategory->id : null,
                'name'            => 'Coca-Cola Zero Sugar Soft Drink',
                'image'           => Storage::disk('public')->url('products/Coca-Cola_Zero_Sugar_Soft_Drink.png'),
                'weight'          => '500 ml',
                'price'           => 44.00,
                'original_price'  => 45.00,
                'discount'        => '2%',
                'delivery_time'   => 10,
                'about_product'   => 'No artificial colors. No added sugar. Gluten free. Enjoy the classic Coca-Cola taste without the sugar.',
                'unit'            => '10',
                'product_code'    => 'CDJ001-005',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $softDrinksSubCategory ? $softDrinksSubCategory->id : null,
                'name'            => 'Paper Boat Zero Lemon Lime Sparkling Drink',
                'image'           => Storage::disk('public')->url('products/Paper_Boat_Zero_Lemon_Lime_Sparkling_Drink.png'),
                'weight'          => '500 ml',
                'price'           => 59.00,
                'original_price'  => 60.00,
                'discount'        => '2%',
                'delivery_time'   => 10,
                'about_product'   => 'A bubbly and aromatic lemon-y ride, hydration has never been tastier! Zero sugar, zero calorie soda water. A sugar-free treat perfect on its own or as a juice mixer.',
                'unit'            => '10',
                'product_code'    => 'CDJ001-006',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $softDrinksSubCategory ? $softDrinksSubCategory->id : null,
                'name'            => 'Pepsi Zero Sugar Soft Drink',
                'image'           => Storage::disk('public')->url('products/Pepsi_Zero_Sugar_Soft_Drink.png'),
                'weight'          => '200 ml',
                'price'           => 40.00,
                'original_price'  => 40.00,
                'discount'        => null,
                'delivery_time'   => 10,
                'about_product'   => 'Enjoy the bold, refreshing taste of Pepsi without the sugar. Perfect for those watching their sugar intake but still wanting the Pepsi taste.',
                'unit'            => '10',
                'product_code'    => 'CDJ001-007',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'id'              => (string) Str::uuid(),
                'sub_category_id' => $softDrinksSubCategory ? $softDrinksSubCategory->id : null,
                'name'            => 'Mirinda Soft Drink',
                'image'           => Storage::disk('public')->url('products/Mirinda_Soft_Drink.png'),
                'weight'          => '500 ml',
                'price'           => 44.00,
                'original_price'  => 45.00,
                'discount'        => '2%',
                'delivery_time'   => 10,
                'about_product'   => 'Orange flavored carbonated soft drink with a bold, fruity taste. Perfect for those who enjoy a tangy, citrusy refreshment.',
                'unit'            => '10',
                'product_code'    => 'CDJ001-008',
                'status'          => 1,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
        ];

        Product::insert($products);
    }
}
